apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    app: webapp
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: webapp
    tier: frontend
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  strategy:
    type: Recreate      # VS RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
      - name: www
        image: pabloqpacin/php_mysqli:v1
        ports:
        - containerPort: 80
          name: www
        volumeMounts:
        - name: www-persistent-storage
          mountPath: /var/www/html
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"
      volumes:
      - name: www-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-apachephp

